(function(m){function z(a,c){for(var b in a)if(Object.prototype.hasOwnProperty.call(a,b)&&!1===c(a[b],b))break}function s(a){for(var c in a)return!1;return!0}function A(a,c,b){try{return a.apply(c,b||[])}catch(d){setTimeout(function(){throw d;},0)}}function B(a,c){function b(){}b.prototype=c.prototype;a.prototype=new b}function t(a){return(a=a.match(J))?a[0]:""}function C(a,c){var b=a.charAt(0);if(!K.test(a))if("."===b)for(a=(c?t(c):f.o)+a,a=a.replace(L,"/"),a=a.replace(M,"$1/");D.test(a);)a=a.replace(D,
"");else a="/"===b?f.domain?f.domain+a.substring(1):a:f.base+a;0===a.indexOf("//")&&(a=location.protocol+a);return a}function N(a,c){function b(){a.onload=a.onerror=a.onreadystatechange=null;n.removeChild(a);a=null;c()}"onload"in a?a.onload=a.onerror=b:a.onreadystatechange=function(){/loaded|complete/.test(a.readyState)&&b()}}function O(a,c){var b=l.createElement("script");N(b,c);b.async=!0;b.src=a;return b}function P(a,c){var b=a.uri,d=(a.n||O)(b,c),e=f.charset;d.charset=e?u(e)?e(b):e:"utf-8";if("SCRIPT"!==
d.nodeName&&(a.d=d,"IMG"===d.nodeName))return;E?n.insertBefore(d,E):n.appendChild(d)}function F(){if(l.currentScript)return l.currentScript;var a;try{h.v()}catch(c){a=c.stack,!a&&window.opera&&(a=(String(c).match(/of linked script \S+/g)||[]).join(" "))}a&&(a=a.split(/[@ ]/g).pop(),a="("==a[0]?a.slice(1,-1):a,a=a.replace(/(:\d+)?:\d+$/i,""));for(var b=l.scripts||(n||l).getElementsByTagName("script"),d=0,e;e=b[d++];)if("interactive"===e.readyState||e.src===a)return e}function G(a,c){for(var b=0,d=
a.length;b<d;b++)if(a[b]===c)return b;return-1}function q(a){return function(c){return{}.toString.call(c)=="[object "+a+"]"}}function Q(a){var c=f.vars;c&&-1<a.indexOf("{")&&(a=a.replace(R,function(a,d){return v(c[d])?c[d]:a}));return a}function H(a,c){var b;p(a)&&(b=a,a="__sync__"+S++);b=h.g(a,b,c);b.f&&(b.e=!0);return b}function w(a,c){var b=H(p(a)?a:[a],!0);h.i(b,function(){for(var a=[],e=0,f=b.a.length;e<f;e++){var k=h.g(b.a[e],null,!1);a.push(k.exports)}a.push(b.exports);A(c,b,a)})}function x(){this.c=
{}}function r(a,c,b,d,e){this.id=a;this.f=d;this.a=c||[];this.exports={};this.parent=e;this.e=b}function y(){this.j={}}if(!m.sojs){var J=/[^?#]*\//,D=/([^\/]*)\/\.\.\/?/,L=/\/\.\//g,M=/([^:/])\/+\//g,K=/^\/\/.|:\//,T=/[^.]\s*require\s*\(\s*["']([^'"\s]+)["']\s*\)/g,U=/(\/\*([\s\S]*?)\*\/|([^:]|^)\/\/(.*)$)/mg,V=/^([^/:]+)(\/.+)$/,W=/^[\.\#]?\w+[^{]+\{[^}]*\}/,R=/{([^{]+)}/g,X=new Function,l=document,S=0,n=l.head||l.getElementsByTagName("head")[0]||l.documentElement,E=(n||l).getElementsByTagName("base")[0],
v=q("String"),u=q("Function"),p=Array.isArray||q("Array"),Y=q("Object"),g=x.prototype;g.t=function(a,c){var b=this.c||(this.c={});b[a]||(b[a]=[]);-1==G(b[a],c)&&b[a].push(c);return c};g.m=function(a,c){var b=this,d=this.t(a,function(){c.apply(this,arguments);b.s(a,d)})};g.b=function(a){if(this.c){var c=this.c[a],b=Array.prototype.slice.call(arguments,1);if(c)for(var d=0,e;e=c[d++];)e.apply(this,b)}};g.s=function(a,c){if(this.c){var b=this.c[a];if(b){var d=G(b,c);-1!==d&&b.splice(d,1)}}};B(r,x);g=
r.prototype;g.h=function(a,c){this.d=a;if(this.f)this.a=[];else{for(var b=(a+"").replace(U,""),d,e=[];d=T.exec(b);)d[1]&&e.push(d[1]);b=c?c.concat(e):e;d={};for(var f=b.length,k=[],e=0;e<f;e+=1)d[b[e]]=b[e];for(e in d)k.push(d[e]);this.a=k}this.b("define",this)};g.l=function(){("amd"===f.mode||this.e)&&this.k();this.b("load",this)};g.k=function(){function a(a,b){return h.require(c(a,d),b)}function c(a,b){p(a)?z(a,function(c,d){a[d]=h.resolve(c,b)}):a=h.resolve(a,b);return a}if(!s(this.exports))return this.exports;
var b=this.d,d=this.uri;a.async=function(a,b){w(c(a,d),b)};(b=u(b)?A(b,m,[a,this.exports={},this]):b)&&(this.exports=b);this.b("exec",this);delete this.e;delete this.d;delete this.f;delete this.parent;delete this.n;return this.exports};B(y,x);g=y.prototype;g.g=function(a,c,b,d,e){if(a instanceof r)return a;f.id=a;this.b("identify",f);a=f.id;var g=h.resolve(a,e&&e.uri),k=this.j[g];k||(k=this.j[g]=new r(a,c,b,d,e),k.uri=g,this.b("resolve",k));k.e||(k.e=b);return k};g.i=function(a,c,b){a=this.g(a,[],
b&&/__sync__/.test(b.id),null,b);a.m("load",c);var d=this;this.q(a,function(){var b=a.a,c=b.length;if(c)for(var f=0,g;g=b[f++];)d.i(g,function(){!--c&&a.l()},a);else a.l()})};g.q=function(a,c){s(a.exports)?(a.m("define",c),a.u||this.b("request",a),a.u||(/__sync__/.test(a.uri)||a.f?a.h(a.d,a.a):P(a,function(){a.h(a.d,a.a)}))):(a.h(a.d,a.a),c())};g.p=function(a,c,b){var d=F();a=a||d.src;var e=this.j[a];e?c&&(e.a=e.a.concat(c)):(e=this.g(a,[],null,!0),e.r=d);e.h(b,c)};g.resolve=function(a,c){if(!a||
W.test(a))return a;var b=a,d=f.alias,b=a=d&&v(d[b])?d[b]:b,d=f.paths,e;d&&(e=b.match(V))&&v(d[e[1]])&&(b=d[e[1]]+e[2]);a=Q(b);e=a.length-1;a="#"===a.charAt(e)?a.substring(0,e):/\w+\.\w+|\/$/.test(a)||0<a.indexOf("?")?a:a+".js";e=C(a,c);b=f.map;d=e;if(b)for(var g=0,h;(h=b[g++])&&(d=u(h)?h(e)||e:e.replace(h[0],h[1]),d===e););return d};g.config=function(a){z(a,function(a,b){var d=f[b];if(d&&Y(d))for(var e in a)d[e]=a[e];else p(d)?a=d.concat(a):"base"===b&&("/"!==a.slice(-1)&&(a+="/"),a=C(a)),f[b]=a});
h.b("config",f)};var h=m.sojs=new y,f={},g=t(location.href),I=g.match(/^.*?\/\/.*?\//);f.dir=f.base=t(F().src)||g;f.o=g;f.mode="cmd";f.domain=I?I[0]:"";h.w=f;h.require=function(a,c,b){if(c)w(a,c);else if(a=H(a,b),b&&!a.f)h.i(a,X);else return s(a.exports)&&!a.r?a.k():a.exports};h.use=function(a,c){var b=f.preload;if(b)h.require(b,function(){h.require(a,c,!0);delete f.preload},!0);else return h.require(a,c,!0)};m.define=function(a,c,b){var d=arguments.length;1==d?(b=a,a=null):2==d&&(b=c,p(a)?(c=a,a=
null):c=null);h.p(a,c,b)};m.require=function(a,c){return h.require(a,c,!0)};require.async=h.require.async=w}})(this);
